# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  github:
    url: https://github.com/shenjoel
    target: _blank
  link:
    text: 友情链接
    url: /
  links1:
    text: 华ing's blog
    url: https://wurh.github.io/
    target: _blank
  links2:
    text: firewood's blog
    url: http://firewood1122.github.io/
    target: _blank

rss: /atom.xml

#你的头像url
avatar: /img/brand.png

# email
email: 372620726@qq.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#22242b'

# Content
tags:
  title: 标签

# 文章截断
excerpt_length: 0
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: false

#是否开启分享
share: true

#是否开启搜索
search: true

#是否大屏幕下文章页隐藏导航
hideMenu: false

#是否开启toc
#toc: false
toc:
  list_number: false  # 是否显示数字排序

#站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

# less
less:
  paths:
    - source/css/style.less

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: shenjoel
